### ISSUE TITLE
Request to add routing

### ISSUE THREAD

**Issue by paul07481** [sjchristi/skobbler-mono-bindings#2]
Love the ability to use SKMaps from Xamarin. Would be great if we could get Routing API working as well.

**Comment by sjchristi** [comment]
Sorry it's been so long since an update; trying to get offline maps working.

I've prototyped the routing API and there is a new example for it.  I haven't exposed the entire API but this is at least a start.  If there are particular features you want from routing API please let me know and I'll try to get to them sooner rather than later.

thanks!

**Comment by paul07481** [comment]
Excellent, I will give it a try. We have done some work on Android and iOS which we could contribute but would like to check some stuff with you first. Would you mind giving me an email I can get hold of you on? mine is paul07481 -at- hotmail.com 
Thanks!

**Comment by Dhanush-S** [comment]
Sorry if this the wrong place to ask.I am not sure where I can ask a question as I am new to GitHub.
I have used the Xamarin bindings and I must say its just great to work with them.My question is apart from Routing API is there any other APIs not exposed currently in these bindings?Would be great help if I could get any info on that.

**Comment by paul07481** [comment]
The routing API is now part implemented. If you wish to see exactly what is still to do you can compare what has been implemented in ApiDefinition.cs with the documented Skobbler API here: http://developer.skobbler.co.uk/docs/ios/2.3.0/index.html.
