### ISSUE TITLE
Binding for SKTools

### ISSUE THREAD

**Issue by Dhanush-S** [sjchristi/skobbler-mono-bindings#6]
Hi,

Are there any plans to create binding for Skobbler v2.4 SKTools?

Regards,
Dhanush

**Comment by sjchristi** [comment]
Dhanush-

Currently, no.  I've just been re-implementing those in pure C# because I'm trying to get towards a unified API for iOS and Android.  I've implemented enough code to do offline map downloading; you can check that out if you are interested.  Is there something in particular from the tools you need/want?  I can check it out.

thanks,
sam

**Comment by Dhanush-S** [comment]
Hi Sam,

Thanks for quick reply.I was in fact interested in offline map downloading itself which you have already implemented.Will have a look at the same.Thanks.

Regards,
Dhanush
